### ISSUE TITLE
Admin Events Not Being Published to Kafka Topic

### ISSUE THREAD

**Issue by zaidmasri** [SnuK87/keycloak-kafka#56]
Hi there!

I’m using the `keycloak-kafka` module (version 1.2.0) with Keycloak 26.1.4, and while user events are being successfully published to the `user_events` Kafka topic, admin events are not appearing in the configured `admin_events` topic. I’d appreciate any guidance on what I might be missing or doing wrong!

### Configuration
Here’s the relevant part of my Docker Compose setup for the Keycloak service:

```yaml
keycloak:
  image: quay.io/keycloak/keycloak:26.1.4
  environment:
    KC_DB: postgres
    KC_DB_URL: jdbc:postgresql://postgres:5432/postgres
    KC_DB_SCHEMA: keycloak
    KC_DB_USERNAME: postgres
    KC_DB_PASSWORD: password
    KC_HOSTNAME: https://keycloak.localhost
    KC_HOSTNAME_PORT: 8080
    KC_HOSTNAME_STRICT: false
    KC_HOSTNAME_STRICT_HTTPS: false
    KC_SPI_EVENTS_LISTENER_KAFKA_EVENTS: CODE_TO_TOKEN,REGISTER,REGISTER_ERROR,LOGIN,LOGIN_ERROR,USER_INFO_REQUEST,USER_INFO_REQUEST_ERROR,LOGOUT,LOGOUT_ERROR
    KC_SPI_EVENTS_LISTENER_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    KC_SPI_EVENTS_LISTENER_KAFKA_TOPIC_EVENTS: user_events
    KC_SPI_EVENTS_LISTENER_KAFKA_ADMIN_TOPIC: admin_events
    KC_SPI_EVENTS_LISTENER_KAFKA_CLIENT_ID: keycloak-kafka-producer
    KC_SPI_EVENTS_LISTENER_KAFKA_MAX_BLOCK_MS: 10000
    KEYCLOAK_ADMIN: admin
    KEYCLOAK_ADMIN_PASSWORD: admin
  volumes:
    - "./keycloak-kafka/target/keycloak-kafka-1.2.0-jar-with-dependencies.jar:/opt/keycloak/providers/keycloak-kafka-1.2.0-jar-with-dependencies.jar"
  command: start-dev
  depends_on:
    traefik:
      condition: service_started
    postgres:
      condition: service_healthy
  networks:
    - app-network
```

### Steps Taken
- Added the `kafka` listener to "Event Listeners" in the Keycloak admin console (Realm Settings > Events > Config).
- Enabled "Save Admin Events" in the admin console for the realm.
- Confirmed `user_events` topic receives messages (e.g., `LOGIN`, `LOGOUT`) as expected.
- Created the `admin_events` topic manually in Kafka (`kafka-topics --create --topic admin_events --partitions 1 --replication-factor 1`).
- Performed admin actions (e.g., creating a user, updating realm settings), but no messages appear in `admin_events` (verified with `kafka-console-consumer`).

### Environment
- **Keycloak Version**: 26.1.4
- **Kafka Version**: Confluent `cp-kafka:7.5.3` (Kafka 3.5.x)
- **Module Version**: `keycloak-kafka-1.2.0`
- **Kafka Config**: `KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"`

### Expected Behavior
Admin events (e.g., `CREATE`, `UPDATE` for users or realms) should be published to the `admin_events` topic when triggered, as per the `KC_SPI_EVENTS_LISTENER_KAFKA_ADMIN_TOPIC` setting.

### Actual Behavior
No messages are published to the `admin_events` topic, while user events work fine in `user_events`.

### Questions
1. Is there an additional configuration step required for admin events beyond setting `KC_SPI_EVENTS_LISTENER_KAFKA_ADMIN_TOPIC`?
2. Does the module support Keycloak 26.1.4 fully, or could this be a compatibility issue?
3. Should I specify admin event types (e.g., `KC_SPI_EVENTS_LISTENER_KAFKA_ADMIN_EVENTS`) like I do for user events, or does it send all admin events by default?

Any insights or suggestions would be greatly appreciated! Let me know if you need more logs or details to diagnose this.

Thanks!
